# Generated by Django 5.1.6 on 2025-03-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_landlord_latitude_landlord_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='pin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
