# Generated by Django 5.1.6 on 2025-03-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_landlord_latitude_alter_landlord_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='landlord_images/'),
        ),
    ]
